id: I7EEFE79E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:21:59+00:00'
last_modified: '2022-06-09T04:45:35.442252+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19048
  title: བོད་ལུགས་གསོ་རིག་སྨན་པའི་ཐོབ་ཐང་རྒྱུགས་བཤེར་གྱི་དྲི་གཞི་འཚོ་བྱེད་རྣམས་ལ་ཉེ་བར་མཁོ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    2A4E:
      image_group_id: I8LS19050
      title: Volume 1 of bod lugs gso rig sman pa'i thob thang rgyugs bsher gyi dri
        gzhi 'tsho byed rnams la nye bar mkho ba/
      total_pages: 332
      order: 1
      base_file: 2A4E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
