id: opecha:P007089
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19048
  title: བོད་ལུགས་གསོ་རིག་སྨན་པའི་ཐོབ་ཐང་རྒྱུགས་བཤེར་གྱི་དྲི་གཞི་འཚོ་བྱེད་རྣམས་ལ་ཉེ་བར་མཁོ་བ།
  volume: ''
  author: ''
