id: P007089
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19048
  title: བོད་ལུགས་གསོ་རིག་སྨན་པའི་ཐོབ་ཐང་རྒྱུགས་བཤེར་གྱི་དྲི་གཞི་འཚོ་བྱེད་རྣམས་ལ་ཉེ་བར་མཁོ་བ།
  author: ''
  volumes:
    7715d287d0eb45c3851a2163c1e04da7:
      image_group_id: I8LS19050
      title: ''
      volume_number: 1
      total_pages: 332
ebook_metadata:
  title: བོད་ལུགས་གསོ་རིག་སྨན་པའི་ཐོབ་ཐང་རྒྱུགས་བཤེར་གྱི་དྲི་གཞི་འཚོ་བྱེད་རྣམས་ལ་ཉེ་བར་མཁོ་བ།
  author: ''
  sku: P007089
  cover: cover.jpg
  layers:
  - pagination
